# fly.toml app configuration file generated for old-grass-3144 on 2023-05-18T10:53:29-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "old-grass-3144"
primary_region = "lax"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true

